services:
  postdb: 
    image: postgres:18
    container_name: postdb
    environment:
      POSTGRES_USER: felipe
      POSTGRES_PASSWORD: dbTreis0303
      POSTGRES_DB: apitreis
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal_db

  treisapi: 
    build: ./
    container_name: treisapi
    ports:
      - "3002:3002"
    environment:
      DB_HOST: postdb 
      DB_USER: felipe
      DB_PASS: ${DB_PASS}
      DB_NAME: apitreis
      ORIGIN: http://localhost:3003
      PEPPER_VERSIONS: ${PEPPER_VERSIONS}
      PEPPER_CURRENT: ${PEPPER_CURRENT}
      ENABLE_CONSOLE_LOG: true
    depends_on:
      - postdb
    networks:
      - internal_db
    env_file:
      - .env.production


volumes:
  postgres_data:

networks:
  internal_db:
    driver: bridge
