-- ==============================================================================
-- DNA DO MOTOR TREIS - SCRIPT DE INICIALIZAÇÃO CORE (POSTGRES 18)
-- Este arquivo define a infraestrutura mínima para o motor funcionar.
-- ==============================================================================

-- 1. Extensões e Configurações
-- O Postgres 18 já possui gen_random_uuid() nativo, mas mantemos para compatibilidade
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Tabela de Usuários (Base de Autenticação)
CREATE TABLE IF NOT EXISTS "vacas_users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "login" VARCHAR(15) NOT NULL UNIQUE,
    "password" VARCHAR(60) NOT NULL,
    "pepper" VARCHAR(3) NOT NULL DEFAULT '1',
    "role" VARCHAR(50) NOT NULL DEFAULT 'regular',
    "status" VARCHAR(20) NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ NULL DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_vacas_users_role ON "vacas_users"("role");
CREATE INDEX IF NOT EXISTS idx_vacas_users_status ON "vacas_users"("status");

-- 3. Tabela de Sessões (Segurança e Auditoria)
CREATE TABLE IF NOT EXISTS "vacas_user_sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    "user_id" INTEGER NOT NULL REFERENCES "vacas_users" ("id") ON DELETE CASCADE,
    "token_hash" VARCHAR(255) NOT NULL UNIQUE,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "is_revoked" BOOLEAN NOT NULL DEFAULT false,
    "ip_address" VARCHAR(45) NOT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_used_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ NULL DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_vacas_user_sessions_user_id ON "vacas_user_sessions"("user_id");
CREATE INDEX IF NOT EXISTS idx_vacas_user_sessions_token_hash ON "vacas_user_sessions"("token_hash");
CREATE INDEX IF NOT EXISTS idx_vacas_user_sessions_expires_at ON "vacas_user_sessions"("expires_at");

-- 4. Função de Manutenção (Limpeza de Sessões Antigas)
-- Pode ser chamada por um cronjob ou worker da API
CREATE OR REPLACE FUNCTION cleanup_old_sessions()
RETURNS void AS $$
BEGIN
    DELETE FROM "vacas_user_sessions" 
    WHERE (expires_at < NOW() - INTERVAL '30 days')
       OR (last_used_at < NOW() - INTERVAL '30 days')
       OR (deleted_at IS NOT NULL AND deleted_at < NOW() - INTERVAL '30 days');
END;
$$ LANGUAGE plpgsql;

