-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           PostgreSQL 17.9 (Debian 17.9-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
-- OS do Servidor:               
-- HeidiSQL Versão:              12.10.0.7000
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Copiando estrutura para tabela public.users
CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "login" VARCHAR(15) NOT NULL UNIQUE,
    "password" VARCHAR(60) NOT NULL,
    "pepper" VARCHAR(3) NOT NULL DEFAULT '1',
    "role" VARCHAR(50) NOT NULL DEFAULT 'regular',
    "status" VARCHAR(20) NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP NULL DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_role ON "users"("role");
CREATE INDEX IF NOT EXISTS idx_users_status ON "users"("status");

-- Copiando dados para a tabela public.users: 2 rows
/*!40000 ALTER TABLE "users" DISABLE KEYS */;
INSERT INTO "users" ("id", "name", "email", "login", "password", "created_at", "updated_at", "deleted_at", "role", "status", "pepper") VALUES
	(1, 'Felipe Trevenzoli', 'felipe.trevenzoli@gmail.com', 'felipe', '$2b$12$ErGGhhjF2HtJkB8cEwFtRuq5dDBqDLqIibwLKiIcPnf16r9YEDjr6', '2025-04-15 23:18:38.36265', '2026-03-10 23:32:08.224', NULL, 'admin', 'active', '1'),
	(16, 'Tatiane Trevenzoli', 'tatiane.trevenzoli@gmail.com', 'tatiane', '$2b$12$LcbfR3JUlwYu3icV2AOS/OrqnR/ZGXkfIhXlA1gkLj/899bSKcoEu', '2025-04-16 23:45:50.649651', '2025-06-08 19:10:10.261', NULL, 'regular', 'active', '1'),
	(39, 'Theodoro', 'theodoro@gmail.com', 'theodoro', '$2b$12$72Jw3mwgIZJs0bLyHn4Yu.6TDPD9A3fOD2yqBxptPBPz/dwDN/dsS', '2025-06-15 22:25:02.57854', '2026-03-09 15:50:57.692', NULL, 'guest', 'active', '1');
/*!40000 ALTER TABLE "users" ENABLE KEYS */;

-- Copiando estrutura para tabela public.user_sessions
-- Garantir que a extensão uuid está disponível
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "user_sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" INTEGER NOT NULL,
    "token_hash" VARCHAR(255) NOT NULL UNIQUE,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "is_revoked" BOOLEAN NULL DEFAULT false,
    "ip_address" VARCHAR(45) NOT NULL,
    "created_at" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    "last_used_at" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP NULL DEFAULT NULL,
    "updated_at" TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT user_sessions_pkey PRIMARY KEY ("id"),
    CONSTRAINT fk_user_sessions_user_id 
        FOREIGN KEY ("user_id") 
        REFERENCES "users" ("id") 
        ON UPDATE NO ACTION 
        ON DELETE CASCADE
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_user_sessions_token_hash ON "user_sessions"("token_hash");
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON "user_sessions"("user_id");
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at ON "user_sessions"("expires_at");
CREATE INDEX IF NOT EXISTS idx_user_sessions_is_revoked ON "user_sessions"("is_revoked");

CREATE OR REPLACE FUNCTION cleanup_old_sessions()
RETURNS void AS '
BEGIN
    DELETE FROM "user_sessions" 
    WHERE (expires_at < NOW() - INTERVAL ''30 days'')
		OR (last_used_at IS NOT NULL AND last_used_at < NOW() - INTERVAL ''30 days'')
		OR (deleted_at IS NOT NULL AND deleted_at < NOW() - INTERVAL ''30 days'');
    
    -- Opcional: Log da limpeza
    RAISE NOTICE ''Limpeza de sessões concluída em %'', NOW();
END;
' LANGUAGE plpgsql;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
