services:
  db_clone:
    # Usando a imagem personalizada que já contém o init.sql e tabelas base
    image: felipetrevenzoli/treis-db:latest
    container_name: treis_clone_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./db-core:/docker-entrypoint-initdb.d/
    networks:
      - treis_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

    # Executa scripts SQL da pasta ./db toda vez que o sistema sobe
  db-migrator:
    image: postgres:18
    depends_on:
      db_clone:
        condition: service_healthy
    volumes:
      - ./db:/scripts
    command: >
      sh -c "until pg_isready -h db_clone -U ${DB_USER}; do sleep 2; done;
            export PGPASSWORD=${DB_PASS};
            for f in /scripts/*.sql; do 
              [ -e \"$$f\" ] && psql -h db_clone -U ${DB_USER} -d ${DB_NAME} -f \"$$f\"; 
            done"
    networks:
      - treis_net

  api_clone:
    build: .
    profiles: ["api"]
    container_name: treis_clone_api
    restart: always
    ports:
      - "3020:3020"
      - "50051:50051"
    env_file: .env
    depends_on:
      db_clone:
        condition: service_healthy
    networks:
      - treis_net

volumes:
  pgdata:

networks:
  treis_net:
    driver: bridge
